language: bash

matrix:
  include:
    - os: linux
      env: FUGUE_RELEASE="2017.05.23" FUGUE_VERSION="0.30.9-1964"
    - os: linux
      env: FUGUE_RELEASE="2017.06.12" FUGUE_VERSION="0.34.11-2156"

env:
  global:
    - secure: "YNOQJlDBRzfcMnPKp2wZ0y7aKw7ieOxW2YReou9F1qoX4dyz6ndcFJzmMV4G6Xo5K0UoejeROYafLO3Js/sLDgCuM+5dyFcAPT45OUVbyiDLX/CPaPFaSB/MyYFyIVeFt0CyUY39SlSt78KXR5k8BYb6K0QzrtbPVOST8PB23Qg7KSq5lIc6XqRY1YB+SXUW44cHCZ6eU4sAPZwWZEw+vBUaz3VrDBDODQhpf1/dkkGh1y1OUqL+0Dq+9LmxlL46GOapj9hmIq6j/cJfDPZSUkpg7Ec1joqsNiGwB0Bv9nlNNi1+jM01ze+GTmVdtgBSzeAx7jrTr6M8lOJlR8JLBYrDKNEpW/HoZ/8RMeO+RhSNRHdbgkrersMquKSrN4uoOAAB0JItlEF1a2ib+5aYy/USJpFdHl9n/QLgYoQPwJnzovTYkhNXYuEzYQPFF8uzlk0b1LluiWnz0t2rBeBJALf4GiSv9LV7qtv8iOFtN0xjNqlfTIf40ROGioyVnNTds/AM2+vEJA0Xf6K7EdyOYygxy0vWEzUiYBscdgYfJlSDoufqccdfjDe9N8k8+bJ7MpKzHcyJV9uNqjYNiLDe0TE9VqmrsZb9Kre+UwmB5SX3TKbgPy1WwqClfC4WCGuklwJArSfjAEsPoRsYW2doZYbjDfHCqI6FcuXKbiw4HDQ="
    - secure: "ZJS75g7WBCFSDKTAVLCU1KOsTSqZB7E9h/SpVc8TZGTlFaVH+DsKOy41rqFPQyQMOhxY5u7slLO8pQzMbtH36Cdh5CGVX3J80gD+HnPra2Oqa0Oe4ZXSE0XAzHJJjQiDW9rMwmx2Iu7sIBniNI2AEqfZN3j8SVVL15zUgaz1MPH/XzkF5D8Vv0LwaQmmlC05DR5J3ayek3KdxrJJ0GafXM2kRmuGumPgg+8jhh8wChV6FvNxehUzAYkJbQ1QY+dG5yLHKTCpXPWSj4n/odxCr/RNKnCtb5dw4mLCoOV4IlpwHN/E2oSWzBFL6PDQPbUAiCXOFNcQxkd562mop2BNpL5FXY+Et3QXvqo4nka8ervWhh4uwDJLNETneUjcwggnBSag0kA788mlDuJ5zWRYO+TBIzbtQ/P0Gf7hQELLJq4AfVj2yr40Wv6U6iyQRHMIolTiUwlUM8moRQUOU6u4wR//iVYX7sd1E26pEfXtSLqB5f8Y9vv1iMzCIfB7ntmCzXHFgcg+bK8L/B+kgjiJaGK+Ct3RjEdCjyDG6uRM1oyr8D3phu+p/DEtYX9cbPLhZ5lvsCMwzFpZgzmm1E4o0oQ9m6x9csJWjjbI8/GGKqcd2It5SfQL7FSmrC0y1dZMZ/pWxrCy4Q+YhiVeeXoFbg77itPkOdPapo5nzvmef88="

before_install:
  - sudo pip install awscli
  - aws s3 cp s3://saboRepo/${FUGUE_RELEASE}/fugue-client_${FUGUE_VERSION}_amd64.deb fugue-cli.deb

install:
  - sudo dpkg --install fugue-cli.deb  

script:
  make 
